/-
Copyright (c) 2026 Anonymous. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anonymous
-/
import Mathlib.Data.ZMod.Basic

/-!
# R025 — Basepoint as compressed state / forgetting structure

Seventh review (2026-08-07), two competing explanations that must now be
separated:

(I) "Losing a whole number field" — YES, via FORGETTING STRUCTURE (not via a
    field homomorphism: a ring hom from a field to a nonzero ring is injective).
    Cleanest: a complex vector space forgotten to a real vector space; the C
    scalar action leaves the observation language, and "multiply by i" survives
    as an operator J : V → V, J² = -I.  The extra data (V, J) determines the
    complex structure: (a+b·i)v = a·v + b·J·v.

    Known baseline: primitive element theorem (finite separable K/F is
    K = F(α)); e.g. F_9 = F_3[α]/(α²+1).  The full extension is generated by
    ONE distinguished element relative to the base field + the relation α² = -1.
    This matches "basepoint self-iteration generates the structure".

(II) "Is the basepoint actually a compressed state (history/iterations/relations)
     rather than an origin?" — must now be treated as a competing explanation.
     Model: h ∈ H is the full history/environment, q : H → E produces the current
     basepoint, B : H → Y is the full generation behavior.  The strict test:
         q(h1) = q(h2)  ⟹  B(h1) = B(h2) ?
     If it holds for ALL h1 h2, then B factors through q (B = Bbar ∘ q): history is
     fully compressed into the basepoint.  If a collision exists
     (q(h1)=q(h2) but B(h1)≠B(h2)), the basepoint is NOT a complete state and a
     residual context exists externally.

     This reuses the R021 non-eliminability witness.  `reflect_implies_factor`
     below is the POSITIVE direction (no collision ⟹ factorization), the
     counterpart of R021.no_elimination.
-/

namespace R025

/-- Positive compression test: if the basepoint map `q` does not collide under
the behavior `B` (every q-fiber is contained in a B-fiber), then `B` factors
through `q`: there is Bbar with B = Bbar ∘ q.  This is exactly "history is fully
compressed into the basepoint" for the behavior B.  The converse (a q-collision
⟹ no factorization) is R021.no_elimination. -/
theorem reflect_implies_factor {H E Y : Type*} (q : H → E) (B : H → Y)
    [Inhabited Y] (href : ∀ h1 h2 : H, q h1 = q h2 → B h1 = B h2) :
    ∃ Bbar : E → Y, ∀ h : H, B h = Bbar (q h) := by
  classical
  -- On the image of q pick a fiber representative; the no-collision hypothesis
  -- makes B constant on each fiber, so the choice is irrelevant.
  let Bbar : E → Y := fun e =>
    if hf : Nonempty {z : H // q z = e} then B (Classical.choice hf).val else default
  refine ⟨Bbar, ?_⟩
  intro x
  -- fiber over q x is nonempty (contains x)
  have hf : Nonempty {z : H // q z = q x} := ⟨⟨x, rfl⟩⟩
  have hB : Bbar (q x) = B (Classical.choice hf).val := by
    unfold Bbar
    rw [dif_pos hf]
  -- the chosen element has q-value = q x, so same B-value as x
  have hq : q (Classical.choice hf).val = q x := (Classical.choice hf).property
  have hbx : B (Classical.choice hf).val = B x := href (Classical.choice hf).val x hq
  rw [hB, hbx]

/-- Cleaner factorization: restrict the codomain to `range q`.  Then NO
`Inhabited Y` and NO arbitrary choice for points outside the image is needed —
every value of the codomain is realized by some h, so the factorization is
canonical.  This is the version that does not hide the boundary in a
`Classical.choice`/default. -/
theorem reflect_implies_factor_range {H E Y : Type*} (q : H → E) (B : H → Y)
    (href : ∀ h1 h2 : H, q h1 = q h2 → B h1 = B h2) :
    ∃ Bbar : Set.range q → Y,
      ∀ h : H, B h = Bbar ⟨q h, ⟨h, rfl⟩⟩ := by
  classical
  -- For e = ⟨q h, hq⟩ pick the witness `e.property.choose` (a canonical choice
  -- from the existence proof itself, not from a Nonempty type), so no separate
  -- arbitrary default is involved.
  let Bbar : Set.range q → Y := fun e => B (e.property.choose)
  refine ⟨Bbar, ?_⟩
  intro h
  -- for e = ⟨q h, ⟨h, rfl⟩⟩, the canonical witness from the property is h.
  have hchoose : q ((⟨q h, ⟨h, rfl⟩⟩ : Set.range q).property.choose) = q h := by
    change q (Exists.choose (show ∃ z : H, q z = q h from ⟨h, rfl⟩)) = q h
    exact (show ∃ z : H, q z = q h from ⟨h, rfl⟩).choose_spec
  have hb : B ((⟨q h, ⟨h, rfl⟩⟩ : Set.range q).property.choose) = B h :=
    href ((⟨q h, ⟨h, rfl⟩⟩ : Set.range q).property.choose) h hchoose
  change B h = B ((⟨q h, ⟨h, rfl⟩⟩ : Set.range q).property.choose)
  exact hb.symm

/-
F_9 = F_3[α]/(α²+1) as pairs (a, b) = a + b·α, with the known multiplication
(a,b)·(c,d) = (ac - bd, ad + bc).  The operator J(a,b) := (-b, a) represents
"multiply by α" (multiply by i in the complex picture).
-/
namespace F9

/-- J(a,b) = (-b, a): "multiply by i/α". -/
def J (v : ZMod 3 × ZMod 3) : ZMod 3 × ZMod 3 := (-v.2, v.1)

/-- J² = -I: applying J twice is negation.  This is the relation α² = -1
transferred to the operator picture. -/
theorem J_sq_neg (v : ZMod 3 × ZMod 3) : J (J v) = (-v.1, -v.2) := by
  ext <;> simp [J]

/-- The scalar action is recovered from (V, J): (a + b·α)·v = a·v + b·J·v.
Verify the multiplication rule on pairs with J = multiply-by-α:
(a,b)·(c,d) = a·(c,d) + b·J(c,d). -/
theorem mul_via_J (a b c d : ZMod 3) :
    (a * c - b * d, a * d + b * c) =
      (a * c + b * (-d), a * d + b * c) := by
  congr
  rw [sub_eq_add_neg, mul_neg]

end F9

end R025
