/-
Copyright (c) 2026 Anonymous. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anonymous
-/
import Mathlib.Data.ZMod.Basic

/-!
# R021 — Anti-Reification / Lambda-Elimination Audit

Fourth review (2026-08-07): the question is NOT "can lambda calculus express a
context" (lambda is powerful enough to encode almost anything), but "is the
context ELIMINABLE from the state representation". Encoding is not elimination.

The rigorous non-eliminability criterion:

  if  ∃ s₁ s₂, P(s₁) = P(s₂)  ∧  O(s₁) ≠ O(s₂),
  then  ¬ ∃ Ō, O = Ō ∘ P      (no factorization).

Proof (one line): if Ō existed then O(s₁) = Ō(P(s₁)) = Ō(P(s₂)) = O(s₂),
contradiction.  P(s₁)=P(s₂) ∧ O(s₁)≠O(s₂) is a strict non-eliminability
witness.  R017 (deleting e₂: same low state, different generated structure)
already provides such a witness; R019 computes the MINIMAL residual R* = the
least information that must be re-encoded.

This file formalizes:
  * no_elimination:  the factorization-impossibility lemma (the core test).
  * definability / unique-expansion: if two expansions of the SAME T₀-reduct
    (i.e. same low-level model) give different observations, then Context is
    not uniquely determined by T₀ — a Beth-style definability obstruction.
-/

namespace R021

/-- Non-eliminability witness (core): if a low-level representation `P` merges
two states but an observable `O` separates them, then `O` does NOT factor
through `P`.  Hence the information carried by the difference is NOT
eliminable from the representation `P`. -/
theorem no_elimination {S M Y : Type*} (P : S → M) (O : S → Y) (s₁ s₂ : S)
    (hP : P s₁ = P s₂) (hO : O s₁ ≠ O s₂) :
    ¬ ∃ Ō : M → Y, ∀ s : S, O s = Ō (P s) := by
  intro h
  rcases h with ⟨Ō, hŌ⟩
  apply hO
  calc
    O s₁ = Ō (P s₁) := hŌ s₁
    _ = Ō (P s₂) := by rw [hP]
    _ = O s₂ := (hŌ s₂).symm

/-- Contrapositive form: if O DOES factor through P, then P must separate every
pair that O separates (P can only refine O). -/
theorem factor_implies_refine {S M Y : Type*} (P : S → M) (O : S → Y)
    (h : ∃ Ō : M → Y, ∀ s : S, O s = Ō (P s)) :
    ∀ s t : S, O s ≠ O t → P s ≠ P t := by
  intro s t hO
  rcases h with ⟨Ō, hŌ⟩
  intro hP
  apply hO
  calc
    O s = Ō (P s) := hŌ s
    _ = Ō (P t) := by rw [hP]
    _ = O t := (hŌ t).symm

/-
The R017/R019 instance (Z/8): low-level representation drops the deleted
freedom entirely (constant), while the observable is closure cardinality.
  P : ZMod 8 → Unit       (low layer keeps nothing of e₂)
  O : ZMod 8 → Nat       (cardinality of the step-e₂ closure)
With e₂ = 4 vs e₂ = 1: P(4) = P(1) (both map to `()`) but O differs
(closure {0,4} has 2 elements vs full space has 8).  Hence no Ō makes
O = Ō ∘ P — the order information of e₂ cannot be eliminated from P.
The minimal residual R* = ord(e₂) is exactly the least info that must be
re-encoded (R019).
-/

namespace ZMod8

open ZMod

/-- The closure cardinality observable on Z/8: O(s) = |{0, s, 2s, ...}|, the
size of the cyclic subgroup generated by s.  (R017/R019: step-s closure.)
Computable: iterate `k • s` for k in 0..8 and count distinct values. -/
def closureSize (s : ZMod 8) : Nat :=
  (List.range 8).toFinset.image (fun k : Nat => (k : ZMod 8) • s) |>.card

/-- The low-layer representation drops the deleted freedom e₂ entirely:
constant map into Unit (R017: P(x,y) = x, so e₂ is invisible to P). -/
def P (_ : ZMod 8) : Unit := ()

/-- O(4) = 2: {0, 4, 8 = 0, ...} has cardinality 2. -/
example : closureSize (4 : ZMod 8) = 2 := by
  native_decide

/-- O(1) = 8: the step-1 closure is the full space. -/
example : closureSize (1 : ZMod 8) = 8 := by
  native_decide

/-- R021 witness (Z/8): P(4) = P(1) (the low layer cannot see e₂), yet
O(4) ≠ O(1).  Hence no Ō : Unit → Nat makes O = Ō ∘ P: the order information
of e₂ cannot be eliminated from the low-layer representation. -/
theorem r021_witness :
    ¬ ∃ Ō : Unit → Nat, ∀ s : ZMod 8, closureSize s = Ō (P s) := by
  apply no_elimination P closureSize (4 : ZMod 8) (1 : ZMod 8)
  · rfl
  · native_decide

/-- The minimal residual (R019): the canonical quotient classes for the
closure-size observable are {0}, {4}, {2,6}, {1,3,5,7} — only 4 classes, so
`ord(e₂)` (the 4 possible orders) is sufficient for the structure type, and the
full e₂ (8 values) is needed only for the exact orbit. -/
example : closureSize (2 : ZMod 8) = closureSize (6 : ZMod 8) ∧
    closureSize (1 : ZMod 8) = closureSize (3 : ZMod 8) := by
  native_decide

end ZMod8

/-- Unique-expansion obstruction (Beth-style): if two expansions of the same
T₀-reduct give different observations, then the context is NOT uniquely
determined by T₀.  Formally: given two interpretation maps I₁ I₂ : C → O from a
fixed context-candidate set C to observations, agreeing on the T₀-reduct but
differing, there is no single T₀-definable function recovering them. -/
theorem unique_expansion_obstruction {C O : Type*} (I₁ I₂ : C → O)
    (h : ∃ c, I₁ c ≠ I₂ c) :
    ¬ ∃ f : C → O, (∀ c, I₁ c = f c) ∧ (∀ c, I₂ c = f c) := by
  intro hf
  rcases h with ⟨c, hc⟩
  rcases hf with ⟨f, hf₁, hf₂⟩
  apply hc
  calc
    I₁ c = f c := hf₁ c
    _ = I₂ c := (hf₂ c).symm

end R021
